# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language: python
        args: [--config=pyproject.toml]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.0.4
    hooks:
    -   id: pycln
        args: [--config=pyproject.toml]